// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_QtBKJHKRl0qMUGW6XYg9dk05n3gmcN4',
    appId: '1:693556950050:web:5405174a67b419f1b0067b',
    messagingSenderId: '693556950050',
    projectId: 'pbl-2025-35a1c',
    authDomain: 'pbl-2025-35a1c.firebaseapp.com',
    storageBucket: 'pbl-2025-35a1c.firebasestorage.app',
    measurementId: 'G-Q039GZ27ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD96pspshH9zDowI-Ka_VFZHKd0K5XlvfM',
    appId: '1:693556950050:android:b423fda38e661196b0067b',
    messagingSenderId: '693556950050',
    projectId: 'pbl-2025-35a1c',
    storageBucket: 'pbl-2025-35a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDFT8p9W0iFr3Li15YORUhmU3X0Usv23I',
    appId: '1:693556950050:ios:ec15a6c6c5b8bc4bb0067b',
    messagingSenderId: '693556950050',
    projectId: 'pbl-2025-35a1c',
    storageBucket: 'pbl-2025-35a1c.firebasestorage.app',
    iosBundleId: 'com.example.jawara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDFT8p9W0iFr3Li15YORUhmU3X0Usv23I',
    appId: '1:693556950050:ios:ec15a6c6c5b8bc4bb0067b',
    messagingSenderId: '693556950050',
    projectId: 'pbl-2025-35a1c',
    storageBucket: 'pbl-2025-35a1c.firebasestorage.app',
    iosBundleId: 'com.example.jawara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_QtBKJHKRl0qMUGW6XYg9dk05n3gmcN4',
    appId: '1:693556950050:web:7d5f949a38cc6f33b0067b',
    messagingSenderId: '693556950050',
    projectId: 'pbl-2025-35a1c',
    authDomain: 'pbl-2025-35a1c.firebaseapp.com',
    storageBucket: 'pbl-2025-35a1c.firebasestorage.app',
    measurementId: 'G-NH3F1M1K6J',
  );
}
