import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:jawara/core/models/rumah_model.dart';
import 'package:jawara/core/providers/rumah_provider.dart';

class TambahDataRumahPage extends StatefulWidget {
  const TambahDataRumahPage({super.key});

  @override
  State<TambahDataRumahPage> createState() => _TambahDataRumahPageState();
}

class _TambahDataRumahPageState extends State<TambahDataRumahPage> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _alamatRumahController = TextEditingController();
  final TextEditingController _rtController = TextEditingController();
  final TextEditingController _rwController = TextEditingController();
  final TextEditingController _kepalaKeluargaController = TextEditingController();
  final TextEditingController _jumlahPenghuniController = TextEditingController();
  String? _selectedStatusKepemilikan;
  bool _isLoading = false;

  @override
  void dispose() {
    _alamatRumahController.dispose();
    _rtController.dispose();
    _rwController.dispose();
    _kepalaKeluargaController.dispose();
    _jumlahPenghuniController.dispose();
    super.dispose();
  }

  void _resetForm() {
    setState(() {
      _alamatRumahController.clear();
      _rtController.clear();
      _rwController.clear();
      _kepalaKeluargaController.clear();
      _jumlahPenghuniController.clear();
      _selectedStatusKepemilikan = null;
    });
    _formKey.currentState?.reset();
  }

  Future<void> _submitData() async {
    if (!_formKey.currentState!.validate()) return;

    // Validasi required fields
    if (_alamatRumahController.text.trim().isEmpty) {
      _showErrorSnackbar('Alamat rumah harus diisi');
      return;
    }

    setState(() => _isLoading = true);

    try {
      // Buat RumahModel dari form data
      final newRumah = RumahModel(
        id: '', // Will be auto-generated by Firestore
        alamat: _alamatRumahController.text.trim(),
        rt: _rtController.text.trim(),
        rw: _rwController.text.trim(),
        kepalaKeluarga: _kepalaKeluargaController.text.trim(),
        jumlahPenghuni: int.tryParse(_jumlahPenghuniController.text.trim()) ?? 0,
        statusKepemilikan: _selectedStatusKepemilikan ?? 'Milik Sendiri',
      );

      // Simpan ke Firestore via Provider
      final provider = context.read<RumahProvider>();
      final success = await provider.addRumah(newRumah);

      setState(() => _isLoading = false);

      if (mounted) {
        if (success) {
          // Show success dialog
          showDialog(
            context: context,
            barrierDismissible: false,
            builder: (context) => AlertDialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              title: Row(
                children: [
                  const Icon(Icons.check_circle, color: Colors.green, size: 28),
                  const SizedBox(width: 12),
                  Text(
                    'Berhasil',
                    style: GoogleFonts.poppins(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ),
              content: Text(
                'Data rumah "${_alamatRumahController.text}" berhasil ditambahkan ke Firestore.',
                style: GoogleFonts.poppins(),
              ),
              actions: [
                TextButton(
                  onPressed: () {
                    Navigator.pop(context); // Close dialog
                    Navigator.pop(context); // Back to list
                  },
                  child: Text(
                    'OK',
                    style: GoogleFonts.poppins(
                      color: const Color(0xFF2988EA),
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
            ),
          );
        } else {
          _showErrorSnackbar(provider.errorMessage ?? 'Gagal menyimpan data rumah');
        }
      }
    } catch (e) {
      setState(() => _isLoading = false);
      if (mounted) {
        _showErrorSnackbar('Error: $e');
      }
    }
  }

  void _showErrorSnackbar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message, style: GoogleFonts.poppins()),
        backgroundColor: Colors.red,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FC),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF1F1F1F)),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          'Tambah Daftar Rumah',
          style: GoogleFonts.poppins(
            color: const Color(0xFF1F1F1F),
            fontSize: 18,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(20),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTextField(
                      'Alamat Rumah',
                      _alamatRumahController,
                      'Masukkan alamat lengkap rumah',
                      Icons.home_rounded,
                      required: true,
                      maxLines: 3,
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: _buildTextField(
                            'RT',
                            _rtController,
                            'RT',
                            Icons.location_on_outlined,
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: _buildTextField(
                            'RW',
                            _rwController,
                            'RW',
                            Icons.location_city_outlined,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      'Kepala Keluarga',
                      _kepalaKeluargaController,
                      'Nama kepala keluarga',
                      Icons.person_outline,
                    ),
                    const SizedBox(height: 16),
                    _buildTextField(
                      'Jumlah Penghuni',
                      _jumlahPenghuniController,
                      'Jumlah orang',
                      Icons.people_outline,
                      keyboardType: TextInputType.number,
                    ),
                    const SizedBox(height: 16),
                    _buildDropdown(),
                    const SizedBox(height: 32),
                    Row(
                      children: [
                        Expanded(
                          child: OutlinedButton(
                            onPressed: _resetForm,
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                              side: const BorderSide(color: Color(0xFF2988EA)),
                            ),
                            child: Text(
                              'Reset',
                              style: GoogleFonts.poppins(
                                color: const Color(0xFF2988EA),
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          flex: 2,
                          child: ElevatedButton(
                            onPressed: _submitData,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: const Color(0xFF2988EA),
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: Text(
                              'Simpan Data',
                              style: GoogleFonts.poppins(
                                color: Colors.white,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
    );
  }

  Widget _buildTextField(
    String label,
    TextEditingController controller,
    String hint,
    IconData icon, {
    bool required = false,
    TextInputType keyboardType = TextInputType.text,
    int maxLines = 1,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label + (required ? ' *' : ''),
          style: GoogleFonts.poppins(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: const Color(0xFF1F1F1F),
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          maxLines: maxLines,
          validator: required
              ? (value) {
                  if (value == null || value.trim().isEmpty) {
                    return '$label harus diisi';
                  }
                  return null;
                }
              : null,
          decoration: InputDecoration(
            hintText: hint,
            prefixIcon: Icon(icon, color: const Color(0xFF2988EA)),
            filled: true,
            fillColor: Colors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFF2988EA), width: 2),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Colors.red),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDropdown() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Status Kepemilikan',
          style: GoogleFonts.poppins(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: const Color(0xFF1F1F1F),
          ),
        ),
        const SizedBox(height: 8),
        DropdownButtonFormField<String>(
          initialValue: _selectedStatusKepemilikan,
          decoration: InputDecoration(
            prefixIcon: const Icon(Icons.key_outlined, color: Color(0xFF2988EA)),
            filled: true,
            fillColor: Colors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFE5E7EB)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFF2988EA), width: 2),
            ),
          ),
          items: ['Milik Sendiri', 'Sewa', 'Kontrak', 'Lainnya']
              .map((status) => DropdownMenuItem(
                    value: status,
                    child: Text(status, style: GoogleFonts.poppins()),
                  ))
              .toList(),
          onChanged: (value) {
            setState(() => _selectedStatusKepemilikan = value);
          },
          hint: Text('Pilih status kepemilikan', style: GoogleFonts.poppins()),
        ),
      ],
    );
  }
}

